### ISSUE TITLE
Reed up on how to implement accounts

### ISSUE THREAD

**Issue by malinrudal** [Kirens/DAT256#71]
**As a** programmer **I want to** know the best way of implementing accounts  **since** that will make the implementation easier and more structured 

# Acceptance Criteria
* [x] decide on a way forward for the implementation

# Definition of done
* [x] Code compiles
* [x] Passes all tests
* [ ] Reviewer runs code on own machine
  * [x] Reviewer 1
  * [ ] Reviewer 2

**Comment by Kirens** [comment]
# Needs
I have identified three important aspects for this project in regards to a account / user data management:
* Since this project is limited in scope I have primarily focused on finding a no-backend solution to a database.
* To simplify interactions I would hope to find something with a natively bound API.
* Since we have a live version on github.io it would also be preferable to have a hosting solution.

# Suggested solution
These two realizations have lead me to Firebase [auth](https://firebase.google.com/docs/auth) and [database](https://firebase.google.com/docs/database). Their free _Spark Plan_ should be sufficient as a testing environment for this project.

# Catches
Initially there seems to straightforward interaction permissions, I would need to investigate this a bit further though to be confident.

One thing that could become a problem is that this database would likely be used for local testing-environments as well, which could render faulty data and invalid states for everyone.

**Comment by Kirens** [comment]
My initial testing demonstrated it would be quite straight forward to authenticate users and write simple rules for read and write access. The packages [firebase](https://www.npmjs.com/package/firebase) and [react-firebaseui](https://www.npmjs.com/package/react-firebaseui) will give us a very platform native API to work with.

As such I am confident to suggest for the coming sprint to implement this.

**Comment by DanielWillim** [comment]
Ser generellt mycket bra ut, undrar dock om du kan utöka på meningen: 
> Initially there seems to straightforward interaction permissions, I would need to investigate this a bit further though to be confident.

**Comment by Kirens** [comment]
Absolut!
Databasen är som ett stort JSON-objekt. Det går att beskriva regler på dessa, så:
```json
{
  "rules": {
    "users": {
      "$uid": {
        ".write": "$uid === auth.uid"
      }
    }
  }
}
```
Betyder att `users['userid'].topscore = 10;` bara kan göras om du är inloggad som `userid`.

Jag har inte testat det i praktiken för att det skulle vara för nära att bara göra all implementation, men jag har försäkrat mig om att det är så det fungerar, vilket jag var lite osäker på innan.

**Comment by DanielWillim** [comment]
Okej om det är en fördel varför ligger det under **Catches**?
